### ISSUE TITLE
User input improvements

### ISSUE THREAD

**Issue by NY00123** [NY00123/refkeen#14]
This issue was opened for tracking the status of user input support, and also for writing details specific to supported games.

Unlike Vanilla/Chocolate Doom, a few of the covered games let you change keyboard/joystick settings from the in-game menus, while Wolf3D also covers the mouse. Additionally, there isn't necessarily a single function for processing input which impacts gameplay.

Game-specific details are following.

Keen Dreams and the Catacombs use IN_ReadControl for getting user input and translating it into data impacting gameplay. Wolfenstein 3D is only using IN_ReadControl in the menus, via wl_menu.c:ReadAnyControl.

IN_ReadControl fills a ControlInfo (CursorInfo) struct with the following fields: button0 & button1, x & y, xaxis & yaxis, dir. In the case of Wolf3D (or at least the sole uses from the menu), there are also button2 & button3.

The button fields are used for specifying actions like shooting, jumping and strafing. xaxis and yaxis encode two direction values, with the valid values being -1, 0 and 1. dir encodes both directions in a single enum value. x and y encode not just the directions themselves, but also their magnitudes. These fields are always 0 or +-127 for a keyboard, while they may have more values for mouse and joystick inputs.

With the exception of the Catacomb Adventure Series, ID_ReadControl only gets data from one device at a time, a keyboard or a joystick.
- A mouse could theoretically be used in Keen Dreams after appropriately hex editing the config file, albeit USL_TearDownCtlPanel would effectively change this to ctrl_Joystick2 instead.
- If such a hex edit is done for Catacomb 3-D, only the mouse will be usable for moving, strafing and the basic shooting action. It'll feel closer to its usage in the Catacomb Adventure Series. An explanation related to the series is given later.
- For Wolfenstein 3D, the device type set for ID_ReadControl will always be a keyboard.

Keen Dreams never makes use of the aforementioned 'x' or 'y' values, so it's only the direction which matters. The data that impacts core gameplay arrives from IN_ReadControl. It may still check for other pressed keys in CheckKeys, say for debug keys or displaying the status screen.

For Catacomb 3-D:
- c3_play.c:PollControls is used as a wrapper over IN_ReadControl. In addition to processing keyboard/joystick input via IN_ReadControl, it separately checks for mouse input, taking two mouse buttons into account and storing mouse motion in separate global variables, mousexmove and mouseymove. If a joystick is used, the (calibrated) distance of the stick from the center determines if the player is running. Otherwise, the right shift key is used as a toggle for this.
- c3_wiz.c:ControlMovement uses the aforementioned input to pick movement and rotation speeds. Data based on mousexmove and mouseymove is accumulated with keyboard/joystick input. For the same magnitude of mouse delta, the player will move forward for a greater distance than backwards.
- This is not all that impacts gameplay, though. In addition to the call to ControlMovement, c3_wiz.c:T_Player also checks for specific hardcoded keys representing special actions, like drinking potions or casting bolts.
- The x and y fields of the struct returned from IN_ReadControl are used just for the aforementioned joystick "running" toggle. Mouse motion updates via mousexmove and mouseymove are the only other way for impacting the speed, on top of the keyboard's "running" toggle.

The Catacomb Adventure Series differs from Catacomb 3-D in the following manners, at the least:
- id_in.c:IN_ReadControl may check for input from any of the supported devices, in the following order of priorities: Mouse (if present/detected), joystick (if calibrated), keyboard. It'll exclusively use input from just one of these.
- As a side-effect, if the mouse is used in a way which impacts gameplay, then keyboard/joystick input will be ignored by IN_ReadControl. This differs from Catacomb 3-D. Other keyboard actions (say for drinking a potion) will still be functional, outside of IN_ReadControl.
- Also, unlike Catacomb 3-D, there's no "running" toggle for moving, just for turning. Additionally, how far the joystick is moved will not impact it at all, so just a keyboard toggle will do it, using the 'V' or 'Tab' key.
- If fast turning is enabled via the keyboard, the impact on the turning speed will be greater than in Catacomb 3-D.
- While ControlMovement still fills mousexmove and mouseymove, most chances are they'll be set to 0, due to being done right after a call to IN_ReadControl, which reads pending mouse motion earlier.
- Therefore, in the Catacomb Adventure Series, it's practically just IN_ReadControl which tells how mouse motion impacts movement and rotations in gameplay. This is similar to running Catacomb 3-D with the mouse as the selected input device (by hex editing CONFIG.C3D).
- The x and y fields of the struct returned from IN_ReadControl are not used at all, except for checks in DisplayStatus that could also be done with the xaxis and yaxis fields.
- Furthermore, DisplayStatus separately checks for hardcoded keys in order to pick a status message, say for using a zapper. In the case of a missile, it also checks the control key, not just the button0 field returned from IN_ReadControl. Since you can't change the shooting key without hex editing the config file, it generally doesn't matter, but this is still the case.

To finish, as written earlier, Wolfenstein 3D doesn't use IN_ReadControl during gameplay. wl_play.c:PollControls is used as a full replacement, including demo recording/playback. Outside of demo playback, it may accumulate input from keyboard, mouse and joystick/gamepad.

**Comment by arrowgent** [comment]
yes i can imagine you'll want to create options/configuration sub menus in the game for input/keybinds
seems like most games either do this in game menus, or from a setup prompt menu before launching the sub-games

since youre using SDL2, hopefully it can be easy to code any & all inputs to key bindings read from a cfg (per game) and stored in memory during those runtimes

as with several of these "monolithic" source port engines,  keeping code separated per game might be required
ie: conflict of code doesnt apply to each game segment

im unsure how well SDL2 works for reading for instance both KB + Controller simultaneously,  like movement with kb but using controller buttons for actions.  could be interesting.
SDL2 should handle replacing mouse with controller thumbstick

you also have to be careful which versions of SDL2 youre coding and compiling with,  latest versions arent always avail for some linux distros.  **SDL2-2.0.16** is the latest, released very recently.
even with that ive had to patch dynamic system libSDL2 to prevent input lockup using a patch `x11_keytounicode.diff` since v2.0.12-2.0.15
at first i was patching static library used when compiling those programs,  this proved unreliable and i kept looking for the solution above.
the error often caused system input unresponsive in gzdoom & zandronum, etc when spamming T, ESC, or TILDE forcing a hard-reset.

progress here allowing users to create their own custom key configurations! _keep it up_

**Comment by arrowgent** [comment]
https://github.com/NY00123/refkeen/releases/tag/release-20210824
went through and tested recent release on linux

in catacomb3d,  if you press ESC in game then the touch icons appear on screen,  these shouldnt appear if that setting is off in CFG `Enable Touch Controls` &

```
touchinput=off
touchinputdebugging=false
```

that didnt seem to happen in keen-dreams


r_shift = run isnt configurable in catacomb dos, and it isnt in reflection keen. (not a button option)
would prefer this to be an autorun toggle & configurable ie: L_Shift


_only tested for 1-2 minutes_

**Comment by NY00123** [comment]
Thanks for your feedback!

I think that I won't change the in-game menus, while any new setting for key binding can be made accessible from the launcher.

While SDL2 is indeed used, the codebase in structured in such a way that a great deal of it isn't directly interacting with SDL2. This means, for instance, that if there's ever a case where SDL2 scancodes should be used for custom key bindings, the scancodes will first be converted to internal codes specific to Reflection Keen. Maybe the conversion will technically do nothing (at least initially), but this is how it can be done.

More generally, the idea is that SDL2 can be used for opening certain input devices (e.g., joysticks), and, whenever the program receives from SDL2 a notification about a keyboard/mouse/joystick event (e.g., a button press), it'll be processed without making a further use of SDL2.

Is x11_keytounicode.diff still relevant? Main reason I'm asking is what I see here, dating back to early 2012 and referring just to the SDL 1.2 branch: https://github.com/libsdl-org/SDL-1.2/issues/659

> in catacomb3d, if you press ESC in game then the touch icons appear on screen, these shouldnt appear if that setting is off in CFG `Enable Touch Controls` &
> 
> ```
> touchinput=off
> touchinputdebugging=false
> ```

Did you have a supported game controller connected by chance? If yes, then this is expected. Originally, before plans eventually changed, I thought that I'd maybe add support for another game which re-uses Catacomb 3-D's menus, and also lets you show help screens with the F1 key. In such a case, the touch icons would show the controller button to use as a replacement for F1.

Eventually, it didn't happen, but the UI can still be used for navigation if it's there. You maybe saw other instances of it, say when entering text in the high scores table or a cheat code.

> r_shift = run isnt configurable in catacomb dos, and it isnt in reflection keen. (not a button option)

This is indeed another example of an additional key binding option that can be added in a future release.

> would prefer this to be an autorun toggle

Given that this wasn't originally supported by the game, I'll need to think about that.

**Comment by arrowgent** [comment]
yeah in debian/ubuntu, the `x11_keytounicode.diff` patch isnt official, users are generally unaware of it and rarely encounter this issue
but certain games lock up the keyboard input (no alt tab etc!) and we're forced to patch source and compile our own libraries
arch linux seems to have its own patch set which this is fixed
note: libsdl1.2
seems the patch.diff i have is called `enableunicodeX11events.patch` which is not the same as `x11_keytounicode.diff`
... _i need to take better notes when i have a /build/ folder_
doing better lately, build.txt instructions, weburl locations, etc
`hg clone --branch SDL-1.2 https://hg.libsdl.org/SDL SDL-1.2-fix`
ah yes, `src/video/x11/SDL_x11events.c``#ifdef X_HAVE_UTF8_STRING` is still not patched by debian


```
touchinput=off
touchinputdebugging=false
```

yes i had steam open and a game controller plugged in
**let me... test**
yep, steam closed.   disconnect controller and the UI **isnt** present
reconnect controller and its present
steam creates its own controller UDEV (actually interferes with other software using the controller, _good job steam_)
now testing with steam loaded but controller disconnected...
steam doesnt not cause the UI to be present


i can understand your point since reflection keen is geared towards bringing the original classics to a modern OS (not dosbox) and retaining as much original as possible with minor QOL features
resolution, video, audio enhancements are nice as well as input features

**Comment by NY00123** [comment]
As of ReflectionHLE v0.40.0, there's experimental support for keyboard and mouse button overrides. The main limitation of them I'm currently aware of, is that these over overrides are full. For instance, you can't use an overridden key for activating a cheat code.

**Comment by NY00123** [comment]
I guess this issue may be closed for now.
